// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateList(arg1) {
  return window['go']['main']['App']['CreateList'](arg1);
}

export function CreateTodo(arg1, arg2) {
  return window['go']['main']['App']['CreateTodo'](arg1, arg2);
}

export function DeleteList(arg1) {
  return window['go']['main']['App']['DeleteList'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetLists() {
  return window['go']['main']['App']['GetLists']();
}

export function GetTodos(arg1) {
  return window['go']['main']['App']['GetTodos'](arg1);
}

export function RenameList(arg1, arg2) {
  return window['go']['main']['App']['RenameList'](arg1, arg2);
}

export function SetTodoCompleted(arg1, arg2) {
  return window['go']['main']['App']['SetTodoCompleted'](arg1, arg2);
}

export function UpdateTodoTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateTodoTitle'](arg1, arg2);
}
