// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateList(arg1:string):Promise<main.List>;

export function CreateTodo(arg1:number,arg2:string):Promise<main.Todo>;

export function DeleteList(arg1:number):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetLists():Promise<Array<main.List>>;

export function GetTodos(arg1:number):Promise<Array<main.Todo>>;

export function RenameList(arg1:number,arg2:string):Promise<main.List>;

export function SetTodoCompleted(arg1:number,arg2:boolean):Promise<main.Todo>;
